version: 2
jobs:
  build:
    docker:
      - image: swift:4.0.2
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=test
          - MYSQL_DATABASE=balance
    steps:
      - checkout
      - run: apt-get update && apt-get install -y apt-utils && apt-get install -y libmysqlclient-dev libssl-dev uuid-dev
      #- run: export DEBIAN_FRONTEND="noninteractive"
      #- run: debconf-set-selections <<< "mysql-server mysql-server/root_password password 'test'"
      #- run: debconf-set-selections <<< "mysql-server mysql-server/root_password_again password 'test'"
      #- run: apt-get install -y python-dev libcurl4-openssl-dev mysql-client mysql-server
      #- run: ./scripts/createDatabaseForTesting.sh 
      - run: swift build
      - run: .build/debug/BalanceServer
      - run: swift test
