version: 2
jobs:
  build:
    docker:
      - image: swift:4.0.2
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=test
          - MYSQL_DATABASE=balance
    steps:
      - checkout
      - run: apt-get update && apt-get install -y apt-utils && apt-get install -y libmysqlclient-dev libssl-dev uuid-dev
      - run: swift build -Xswiftc -DCIRCLECI
      - run: swift test -Xswiftc -DCIRCLECI

